const files = [
  "6Monsters_Behemoth_Talk_04",
  "6Monsters_BlackBoss_Scream_04",
  "6Monsters_DeadBaby_Talk_01",
  "6Monsters_TwinHead_Death_03",
  "8bit-explosion",
  "ANIMAL_Horse_Neigh_03_Wet_mono",
  "ANIMAL_Tiger_Growl_03",
  "AUDIENCE_Bhoos_02_stereo",
  "AUDIENCE_Clapping_Hall_01_Crop2_stereo",
  "AUDIENCE_Clapping_Hall_07_stereo",
  "AUDIENCE_Claps_and_Cheers_10_stereo",
  "AUDIENCE_Hahaha_01_stereo",
  "BATTLE_Medieval_Reinact_Footsoldiers_Knights_01_loop_stereo",
  "BR AK47 Burst With Tail",
  "Card_Game_Achievement_Shimmer_Long_01",
  "Card_Game_Magic_Glitter_Missile_03",
  "Card_Game_Movement_Deal_Multiple",
  "Card_Game_Upgrade_Buff_Shield_03",
  "Crowd,Bar  Pub,Male,Boo,Aww,Friendly Disappointment",
  "DEMOLISH_Wood_Metal_Deep_stereo",
  "Dragon Tail 1",
  "DRINK_Long_mono",
  "DRINK_Pour_Liquid_In_Glass_Splashy_mono",
  "EAT_Apple_Chewing_Closed_Mouth_x4_loop_mono",
  "electric-shok",
  "FOOTSTEPS_Leather_Wood_Hollow_Sneak_x8_loop_mono",
  "FOOTSTEPS_Leather_Wood_Hollow_Walk_x8_loop_mono",
  "FOOTSTEPS_Trainers_Gravel_Compact_Walk_Slow_x8_loop_mono",
  "FOOTSTEPS_Trainers_Wood_Boards_Walk_x8_loop_mono",
  "GATE_Metal_Close_01_Mid_stereo",
  "ghosty",
  "LOTUS_FLUTE_Whistle_Down_Wobble_01_mono",
  "MUSIC_EFFECT_Orchestral_Battle_Negative_stereo",
  "MUSIC_EFFECT_Platform_Positive_02_stereo",
  "MUSIC_EFFECT_Solo_Clean_Sawtooth_Positive_10_stereo",
  "MUSIC_EFFECT_Solo_Harp_Negative_09_stereo",
  "MUSIC_EFFECT_Solo_Harp_Positive_14_stereo",
  "MUSIC_EFFECT_Space_Synth_Negative_01b_stereo",
  "ps2-whoosh",
  "PUZZLE_Success_Bell_Voice_Three_Note_Climb_Wet_stereo",
  "SPACE_WARP_Complex_04_Deep_stereo",
  "SPACE_WARP_Type_03_Warp_B_stereo",
  "SPLASH_Big_Rumble_Noise_stereo",
  "THUNDER_Clap_Rumble_02_stereo",
  "VOICE_Boy_6yo_Scream_01_mono",
  "VOICE_Boy_6yo_Thank_You_01",
  "VOICE_Female_36yo_Scream_Deep_01_mono",
  "VOICE_Male_Haha_Mocking_02_mono",
];

export default files;
